name: liver_aid
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_liver_aid.png
  color_dark: "#000000"
  image_dark: assets/splash_liver_aid.png
