name: liver_aid
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  fluttertoast: ^8.2.10
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  gap: ^3.0.1
  clipboard: ^0.1.3
  dio: ^5.7.0
  hive_flutter: ^1.1.0
  get: ^4.6.6
  shared_preferences: ^2.4.0
  fluentui_system_icons: ^1.1.271
  open_file: ^3.5.10
  package_info_plus: ^8.1.3
  device_info_plus: ^11.2.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_liver_aid.png
  color_dark: "#000000"
  image_dark: assets/splash_liver_aid.png
